events {
    worker_connections 1024;
}

http {
    upstream fastapi_workers {
        server worker1:8000;
        server worker2:8000;
        server worker3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://fastapi_workers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
